# Generated by Django 3.2.9 on 2022-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20220321_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersOfStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ManyToManyField(related_name='teachers', to='school.Student')),
            ],
        ),
    ]
